### ISSUE TITLE
crash upon sending message

### ISSUE THREAD

**Issue by yoursunny** [named-data/ChronoChat#1]
Version: 0.5.0-0-ppa1~trusty

Step to reproduce:
1. join two chatrooms
2. send a message

Expected: message is sent, and ChronoChat is still running
Actual: crash

```
Starting program: /usr/bin/ChronoChat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "ChronoChat.Conf" because it is missing required fields: identity
"sni-qt/15542" WARN  01:46:18.124 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
[New Thread 0x7fffe4c2a700 (LWP 15545)]
QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe4c2a700 (LWP 15545)]
0x00007ffff3f75b40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff3f75b40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000057405b in ?? ()
#2  0x0000000000571ff0 in ?? ()
#3  0x000000000057555c in ?? ()
#4  0x000000000055a35e in ?? ()
#5  0x000000000055e5c4 in ?? ()
#6  0x000000000055edc3 in ?? ()
#7  0x00000000005646bc in ?? ()
#8  0x0000000000528db3 in ?? ()
#9  0x00000000005581c2 in ?? ()
#10 0x00000000004e56ce in ?? ()
#11 0x00000000004defed in ?? ()
#12 0x0000000000538299 in ?? ()
#13 0x00000000005379f3 in ?? ()
#14 0x00000000004be90e in ?? ()
#15 0x00000000004bdef6 in ?? ()
#16 0x00007ffff50faa4a in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#17 0x00007ffff530d182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#18 0x00007ffff3f27fbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Pesa** [comment]
Closing old/stale issue.
