### ISSUE TITLE
crash upon closing chatroom

### ISSUE THREAD

**Issue by yoursunny** [named-data/ChronoChat#2]
Version: 0.5.0-0-ppa1~trusty

Step to reproduce:
1. join one chatroom
2. right click on tray icon, select _Close Chatroom_ and the chatroom name

Expected: leaving chatroom
Actual: crash

```
Starting program: /usr/bin/ChronoChat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "ChronoChat.Conf" because it is missing required fields: identity
"sni-qt/15603" WARN  01:55:25.021 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
[New Thread 0x7fffe4c2a700 (LWP 15604)]
QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e86d25 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) bt
#0  0x00007ffff6e86d25 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#1  0x00007ffff6e86269 in QApplication::x11ProcessEvent(_XEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#2  0x00007ffff6eadb02 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#3  0x00007ffff3750e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff3751048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff37510ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7a9f7a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff6eadbb6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007ffff7a710af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff7a713a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007ffff7a76b79 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x000000000044e3cc in ?? ()
#12 0x00007ffff3e4eec5 in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#13 0x0000000000457ded in ?? ()
```

**Comment by Pesa** [comment]
Closing old/stale issue.
